when:
  - event: [push, tag, manual]
    branch: [main, preview]

steps:
  - name: web
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: registry.digiconseil.fr
      repo: registry.digiconseil.fr/sites-vitrines/admin-solutions/web
      dockerfile: Dockerfile.web
      context: .
      tags:
        - ${CI_COMMIT_SHA}
      username:
        from_secret: harbor_ci_user
      password:
        from_secret: harbor_ci_password

  - name: deploy
    image: alpine/k8s:1.31.4
    environment:
      KUBECONFIG_DATA:
        from_secret: kubeconfig
    commands:
      - mkdir -p /root/.kube
      - printf '%s\n' "$KUBECONFIG_DATA" > /root/.kube/config
      - kubectl -n client-admin-solutions set image deploy/admin-solutions-web web=registry.digiconseil.fr/sites-vitrines/admin-solutions/web:$${CI_COMMIT_SHA}
      - kubectl -n client-admin-solutions rollout status deploy/admin-solutions-web --timeout=180s
    when:
      - branch: main

  - name: deploy-preview
    image: alpine/k8s:1.31.4
    environment:
      KUBECONFIG_DATA:
        from_secret: kubeconfig
    commands:
      - mkdir -p /root/.kube
      - printf '%s\n' "$$KUBECONFIG_DATA" > /root/.kube/config
      - kubectl -n client-admin-solutions set image deploy/admin-solutions-preview-web web=registry.digiconseil.fr/sites-vitrines/admin-solutions/web:$${CI_COMMIT_SHA}
      - kubectl -n client-admin-solutions rollout status deploy/admin-solutions-preview-web --timeout=180s
    when:
      - branch: preview
