when:
  - event: [push, tag, manual]
    branch: main

steps:
  - name: web
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: registry.digiconseil.fr
      repo: registry.digiconseil.fr/sites-vitrines/admin-solutions/web
      dockerfile: Dockerfile.web
      context: .
      tags:
        - ${CI_COMMIT_SHA}
      username:
        from_secret: harbor_ci_user
      password:
        from_secret: harbor_ci_password

  - name: api
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: registry.digiconseil.fr
      repo: registry.digiconseil.fr/sites-vitrines/admin-solutions/api
      dockerfile: Dockerfile.api
      context: .
      tags:
        - ${CI_COMMIT_SHA}
      username:
        from_secret: harbor_ci_user
      password:
        from_secret: harbor_ci_password

  - name: deploy
    image: bitnami/kubectl:latest
    environment:
      KUBECONFIG_DATA:
        from_secret: kubeconfig_prod
    commands:
      - mkdir -p /root/.kube
      - echo "$KUBECONFIG_DATA" | base64 -d > /root/.kube/config
      - kubectl -n sv-admin-solutions set image deploy/web web=registry.digiconseil.fr/sites-vitrines/admin-solutions/web:${CI_COMMIT_SHA}
      - kubectl -n sv-admin-solutions set image deploy/api api=registry.digiconseil.fr/sites-vitrines/admin-solutions/api:${CI_COMMIT_SHA}
      - kubectl -n sv-admin-solutions rollout status deploy/web --timeout=180s
      - kubectl -n sv-admin-solutions rollout status deploy/api --timeout=180s
