when:
  - event: [push, tag, manual]
    branch: main

steps:
  - name: web
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: registry.digiconseil.fr
      repo: registry.digiconseil.fr/sites-vitrines/admin-solutions/web
      dockerfile: Dockerfile.web
      context: .
      tags:
        - ${CI_COMMIT_SHA}
      username:
        from_secret: harbor_ci_user
      password:
        from_secret: harbor_ci_password

  - name: api
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      registry: registry.digiconseil.fr
      repo: registry.digiconseil.fr/sites-vitrines/admin-solutions/api
      dockerfile: Dockerfile.api
      context: .
      tags:
        - ${CI_COMMIT_SHA}
      username:
        from_secret: harbor_ci_user
      password:
        from_secret: harbor_ci_password
