
networks:
  proxy:
    external: true
  internal:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: adminsolution-web
    networks:
      - proxy
      - internal
    environment:
      # Prod + préprod
      - VIRTUAL_HOST=adminsolution.fr,www.adminsolution.fr,adminsolution.digiconseil.fr
      - LETSENCRYPT_HOST=adminsolution.fr,www.adminsolution.fr,adminsolution.digiconseil.fr
      - LETSENCRYPT_EMAIL=contact@digiconseil.fr
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads:rw
    restart: unless-stopped


